### ISSUE TITLE
No save on partial change

### ISSUE THREAD

**Issue by zebapy** [Arcath/sass-watch#2]
Some reason my main file doesn't compile if it has imports of partials, and they are changed. Am I doing something wrong or is this just missing?

main.scss (file being watched)

```
// core
@import "variables";
@import "mixins";

// base
@import "grids";

// modules
@import "media";
```

partials are `_media.scss` format in same folder as main.scss

**Comment by Arcath** [comment]
0.2.0 now supports rendering the main file if a partial is changed.
