### ISSUE TITLE
Compile fails even though it shouldn't

### ISSUE THREAD

**Issue by Northcode** [Arcath/sass-watch#5]
Command failed: /bin/sh -c /home/username/.atom/packages/sass-watch/node_modules/.bin/node-sass "/home/username/flaskproject/static/style.sass" "style.css"
/usr/bin/env: node: Not a directory

my /usr/bin/node points to /usr/bin/nodejs and is executable from command line

works from zsh but not sh

**Comment by Northcode** [comment]
atom version is: 0.187.0
node is: v0.10.25
sass-watch is: 0.2.0
system: ubuntu 14.10

**Comment by Arcath** [comment]
Sounds to me like its because child_process uses its own partial shell when running the commands.

I am looking at either using the bundled node in atom or requiring node-sass in atom (many issues with doing that atm)

**Comment by Arcath** [comment]
0.3.0 now uses the bundled node. please let me know if that sorts your issue.

**Comment by Northcode** [comment]
Forgot to close this issue sorry.
