### ISSUE TITLE
SASS Compile Failed

### ISSUE THREAD

**Issue by Bartozzz** [Arcath/sass-watch#7]
When I am trying to compile a `.scss` file, I get this error:

```
Command failed: /bin/sh -c "/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/resources/app/apm/bin/node" "/Users/Bartek/.atom/packages/sass-watch/node_modules/node-sass/bin/node-sass" "/Users/Bartek/Sites/_szablony/bartozzz.github.io/styles/template.scss" "/Users/Bartek/Sites/_szablony/bartozzz.github.io/styles/template.css"
/bin/sh: /Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS/resources/app/apm/bin/node: No such file or directory
```

Under the `/Applications/Atom.app/Contents/Frameworks/Atom Helper.app/Contents/MacOS` path I only have `Atom Helper`, there's no `resources/app/apm/bin/node`. Any ideas how can I fix it?

I am working on a new MacBook Pro with:
- node.js   v0.12.0
- node-sass 3.2.0   (Wrapper)   [JavaScript]
- libsass   3.2.5   (Sass Compiler) [C/C++]

**Comment by Arcath** [comment]
In the package settings there is a node binary option if you change it to the output of `which node` that should sort it.

**Comment by Bartozzz** [comment]
Thanks, works like a charm.
